config/routes.rb
require 'sidekiq'
require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  devise_for :user, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register" }

  namespace :admin do
    resources :blogs
    resources :subscriptions
  
    resources :reviews do
      collection do
        get :new_csv
        post :import_csv
        get :delete_all
        get :download_csv
      end
    end
    resources :recommendations
    resources :deals
    resources :announcements

    root to: "reviews#index"
  end

  namespace :api do
    namespace :v1 do
      devise_scope :user do
        post '/login', to: 'sessions#create'
        delete '/logout', to: 'sessions#destroy'
      end
      get '/', to: 'home#index'
      get '/deals', to: 'home#deals'
      get '/filters', to: 'properties#filters'
      post '/contact-us', to: 'contact#contact_thank_you'
      post '/properties', to: 'properties#index'
      post '/property/:id', to: 'properties#show'
      post '/property/stay/:id', to: 'properties#stay'
      post '/property/availability/:id', to: 'properties#calendar_availability'
      # resources :properties, only: %i(index show)
      get '/announcements', to: 'announcements#index'
      resources :triggers, only: :create
      resources :blogs

      resources :subscriptions, only: [:new, :create]

    end
    resources :units, only: [:index, :show] do
      resources :stays, only: [:get]
    end
  end

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

end

app/controllers/admin/reviews_controller.rb
module Admin
  class ReviewsController < Admin::ApplicationController
    def import_csv
      created = 0
      updated = 0
      csv_file = params[:csv_file]
      CSV.foreach(csv_file.path, encoding: "UTF-8", :headers => true) do |row|
        review = Review.find_by(id: row["id"]) || Review.where(first_name: row["first_name"]&.strip, last_name: row["last_name"]&.strip, unit_id: row['unit_id']&.strip).first
        if review.present?
          review.update(review_params(row))
          updated += 1
        else
          Review.create(review_params(row))
          created += 1
        end
      end
      redirect_to admin_reviews_path, notice: "CSV file imported successfully! Created: #{created} Updated: #{updated}"
    end
    def download_csv
      respond_to do |format|
        format.csv { send_data Review.to_csv, filename: "reviews-#{DateTime.now.strftime("%d%m%Y%H%M")}.csv"}
      end
    end

    def delete_all
      Review.destroy_all
      redirect_to admin_reviews_path, notice: "All reviews have been removed"
    end

    private

    def review_params(row)
      {
        first_name: row['first_name']&.strip,
        last_name: row['last_name']&.strip,
        unit_id: row['unit_id']&.strip,
        comment: row['comment']&.strip,
        stars: row['stars']&.strip,
        date:  row['date']&.strip
      }
    end

    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/views/admin/reviews/_collection.html.erb
<%#
# Collection

This partial is used on the `index` and `show` pages
to display a collection of resources in an HTML table.

## Local variables:

- `collection_presenter`:
  An instance of [Administrate::Page::Collection][1].
  The table presenter uses `ResourceDashboard::COLLECTION_ATTRIBUTES` to determine
  the columns displayed in the table
- `resources`:
  An ActiveModel::Relation collection of resources to be displayed in the table.
  By default, the number of resources is limited by pagination
  or by a hard limit to prevent excessive page load times

[1]: http://www.rubydoc.info/gems/administrate/Administrate/Page/Collection
%>

<table aria-labelledby="<%= table_title %>">
  <thead>
    <tr>
      <% collection_presenter.attribute_types.each do |attr_name, attr_type| %>
        <th class="cell-label
        cell-label--<%= attr_type.html_class %>
        cell-label--<%= collection_presenter.ordered_html_class(attr_name) %>"
        scope="col"
        role="columnheader"
        aria-sort="<%= sort_order(collection_presenter.ordered_html_class(attr_name)) %>">
        <%= link_to(sanitized_order_params(page, collection_field_name).merge(
          collection_presenter.order_params_for(attr_name, key: collection_field_name)
        )) do %>
        <%= t(
          "helpers.label.#{collection_presenter.resource_name}.#{attr_name}",
          default: attr_name.to_s,
        ).titleize %>
            <% if collection_presenter.ordered_by?(attr_name) %>
              <span class="cell-label__sort-indicator cell-label__sort-indicator--<%= collection_presenter.ordered_html_class(attr_name) %>">
                <svg aria-hidden="true">
                  <use xlink:href="#icon-up-caret" />
                </svg>
              </span>
            <% end %>
          <% end %>
        </th>
      <% end %>
      <% [valid_action?(:edit, collection_presenter.resource_name),
          valid_action?(:destroy, collection_presenter.resource_name)].count(true).times do %>
        <th scope="col"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% resources.each do |resource| %>
      <tr class="js-table-row"
          <% if show_action? :show, resource %>
            <%= %(tabindex=0 role=link data-url=#{polymorphic_path([namespace, resource])}) %>
          <% end %>
          >
        <% collection_presenter.attributes_for(resource).each do |attribute| %>
          <td class="cell-data cell-data--<%= attribute.html_class %>">
            <% if show_action? :show, resource -%>
              <a href="<%= polymorphic_path([namespace, resource]) -%>"
                 tabindex="-1"
                 class="action-show"
                 >
                <%= render_field attribute %>
              </a>
            <% else %>
              <%= render_field attribute %>
            <% end -%>
          </td>
        <% end %>

        <% if valid_action? :edit, collection_presenter.resource_name %>
          <td><%= link_to(
            t("administrate.actions.edit"),
            [:edit, namespace, resource],
            class: "action-edit",
          ) if show_action? :edit, resource%></td>
        <% end %>

        <% if valid_action? :destroy, collection_presenter.resource_name %>
          <td><%= link_to(
            t("administrate.actions.destroy"),
            [namespace, resource],
            class: "text-color-red",
            method: :delete,
            data: { confirm: t("administrate.actions.confirm") }
          ) if show_action? :destroy, resource %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/reviews/index.html.erb
<% content_for(:title) do %>
  <%= display_resource_name(page.resource_name) %>
<% end %>

<header class="main-content__header" role="banner">
  <h1 class="main-content__page-title" id="page-title">
    <%= content_for(:title) %>
  </h1>

  <% if show_search_bar %>
    <%= render(
      "search",
      search_term: search_term,
      resource_name: display_resource_name(page.resource_name)
    ) %>
  <% end %>

  <div>
    <%= link_to(
      t(
        "administrate.actions.new_resource",
        name: page.resource_name.titleize.downcase
      ),
      [:new, namespace, page.resource_path.to_sym],
      class: "button",
    ) if valid_action?(:new) && show_action?(:new, new_resource) %>
    <%= link_to('Import CSV', new_csv_admin_reviews_path, class: 'button', remote: false) %>
     <%= link_to('Download Reviews', download_csv_admin_reviews_path(format: 'csv'), class: 'button', remote: false) %>
    <%= link_to('Delete all reviews', delete_all_admin_reviews_path, class: 'button', remote: false) %>
  </div>
</header>

<section class="main-content__body main-content__body--flush">
  <%= render(
    "collection",
    collection_presenter: page,
    collection_field_name: resource_name,
    page: page,
    resources: resources,
    table_title: "page-title"
  ) %>

  <%= paginate resources, param_name: '_page' %>
</section>

app/views/admin/reviews/new_csv.html.erb
<% content_for(:title) do %>
    import csv file
<% end %>

<header class="main-content__header" role="banner">
    <h1 class="main-content__page-title" id="page-title">Import CSV file</h1>
    <div>
        <%= link_to('Back', admin_reviews_path, class: 'button') %>
    </div>
</header>

<section class="main-content__body">
<div style="text-align: center;">
 <%= link_to('Download Sample', '/review-sample.csv',download: '', class: 'button') %>
 </div>
    <%= form_tag import_csv_admin_reviews_path, class: 'form', id: 'new_csv', multipart: true %>
        <div class="field-unit field-unit--string field-unit--required">
            <div class="field-unit__label">
                <label for="csv_file">CSV File</label>
            </div>
            <div class="field-unit__field">
                <%= file_field_tag :csv_file%>
            </div>
        </div>
        <div class="form-actions">
            <input type="submit" name="commit" value="Import CSV">
        </div>
    </form>
</section>